### ISSUE TITLE
WAK pin

### ISSUE THREAD

**Issue by bertrik** [maarten-pennings/CCS811#11]
Hi, this is not really an issue, but I don't know of another to communicate about this library.

I've been playing both with this library and the sparkfun CCS811 library and I'm trying to build a CCS811 sensor with environmental (temperature / humidity) compensation. With the Sparkfun library, a CCS811 and a BME280, I've had trouble because of I2C problems (I think). With the CCS811 and the BME280 on the same I2C bus I have problems communicating with both devices (on different i2c addresses obviously), *unless* I manually switch the WAKE pin.

I think this library is taking a very smart approach to specifying the WAKE pin in the constructor of the driver.

**Comment by maarten-pennings** [comment]
Thanks for the compliments on the wake pin in the constructor.

You put a lot of information in a few sentences, so it is a bit hard to understand which combination does not work. Do you need help with something?
