### ISSUE TITLE
SetBaseline bounds

### ISSUE THREAD

**Issue by BorisDess** [maarten-pennings/CCS811#26]
Hello,
I played around with the set_baseline.
I don't know if this can be really considered as an issue but I wanted to share on it as it seems that the baseline if a very important parameter.
Unfortunately it seems that there's ranges where the baseline works, ranges where it does not.

When setting the baseline manually, the maximum value is 3327, the lower value is 173.
When inputing -1, the baseline is 65535, which is the maximum value of the uint16_t C type, minus ( 65536 -1). So the maximum baseline in minus working  value, is -83 (Baseline = 65536-83 = 65453 ).

Other numbers gives what seems to be an "automatic" baseline.
Oh you thought there was only top minus and upper bounds?

It also work between :
~11000 to ~14000 and
~21500 to ~24500 and
32173 to 35071 and,
~43000 to ~46300 and,
~54000 to ~56500 and,
~64500 to 65535.

**Comment by maarten-pennings** [comment]
I'm not sure what you want to achieve. This chip deliberately keeps the baseline values "secret" so that we, as users, can not set a value. As the datasheet states: 
>BASELINE Register (0x11)
>A two byte read/write register which contains an encoded 
>version of the current baseline used in Algorithm Calculations. 
>A previously stored value may be written back to this two byte register
So, it is encoded, and we should only write back what we read.

**Comment by BorisDess** [comment]
Actually I plan to retrieve the baseline to try to see if it can be useful in anyway when putting up the CCS811 against dedicated VOC sensors. I really need to get down to the manufacturer datasheet.

However yes indeed in no mean I want to set it myself.
I just observed that and thought it was worth sharing.
