### ISSUE TITLE
 hex.py

### ISSUE THREAD

**Issue by smartboxchannel** [maarten-pennings/CCS811#32]
>>> python hex.py CCS811_FW_App_v2-0-1.bin > CCS811_FW_App_v2-0-1.h
  File "<stdin>", line 1
    python hex.py CCS811_FW_App_v2-0-1.bin > CCS811_FW_App_v2-0-1.h
             ^
SyntaxError: invalid syntax

**Comment by maarten-pennings** [comment]
This is a bit cryptic.
What we you doing and what is the problem?

**Comment by maarten-pennings** [comment]
Hi, I have added the 2-0-1 header file for your convenience.
