### ISSUE TITLE
Also hex.py

### ISSUE THREAD

**Issue by classiphil** [maarten-pennings/CCS811#34]
I tried to dump Version 2-0-1 as my sensor is older.

I get: 

  File "hex.py", line 32
    if( n%16==0 ): print( "  ", end="" )
                                   ^
SyntaxError: invalid syntax

Thanks for helping.
Maybe you could offer a dump of 2-0-1? 
I already flashed 2-0-0 with your great tool. Should I just let it be? But my sensor is already burned in.

**Comment by maarten-pennings** [comment]
Hi, I have added the 2.0.1 header file.
Note however, that when the sensor has run for a couple of days, you don't see any difference between 2-0-0 and 2-0-1.
