### ISSUE TITLE
flashing on ESP32 required to slow it down

### ISSUE THREAD

**Issue by viperho** [maarten-pennings/CCS811#39]
The sketch css811flash was failing on an ESP32. But once I added the line:
`setCpuFrequencyMhz(80);`
it worked well.

Many thanks for the tool.

**Comment by maarten-pennings** [comment]
That's strange. The only things I can imagine is that there was a mismatch between the actual CPU frequency and the CPU frequency assumed by the I2C block. And the setCpuFrequency fixed that...
