### ISSUE TITLE
eco2=0 ppm,  etvoc=0 ppb

### ISSUE THREAD

**Issue by JohnnyPP** [maarten-pennings/CCS811#4]
Hi,

on ESP8266 I get always the same results of eco2=0 ppm and etvoc=0 ppb. The output looks like this:
CCS811: eco2=0 ppm,  etvoc=0 ppb,  errstat=90=--vhxmrwF--Ad-ie=ERROR|OLD,  raw6=10 uA, raw10=407 ADC. The raw10 varies a little bit but stays in a range between 400 and 420. What could cause this behavior?

**Comment by maarten-pennings** [comment]
Sorry for the late reply?
Is your sketch working now?
If not, could you also show the prints from the beginning of the sketch?
Since the D bit is never hi in STATUS, maybe the start command failed.

**Comment by maarten-pennings** [comment]
Shall I close the issue?

**Comment by bfaliszek** [comment]
I have a very similar problem. After uploading ccs811basic.ino I get ```CCS811: errstat = 10 = - vhxmrwf - Ad-ie``` or ``` CCS811: I2C error```. I am using ESP8266 (NodeMCU) and ccs811 on a purple PCB. Sometimes after several NodeMCU reboots, the code starts working and measurements appear.

**Comment by maarten-pennings** [comment]
Can you show the entire output (from the beginning of the program)?

**Comment by bfaliszek** [comment]
I changed the wires to other ones and now it works. I guess it was just a connection problem.

**Comment by maarten-pennings** [comment]
Good you solved it 👍
