### ISSUE TITLE
CCS811 bricked???

### ISSUE THREAD

**Issue by JohnBelushi** [maarten-pennings/CCS811#46]
Hello Maarten,
I have a CCS811 with old firmware and tried to flash it... that failed.. it was firmware 1.1
And when I run the flasher again it is like you showed a version FD...
Used a Arduino Autonomo and it say's it starts th eflashing procedure but after 15 minutes it still is not ready...

Any idea to get this working again???
Have the nWake pin connected to GND I am not sure if that's a problem??

Best regards,
Jody

**Comment by maarten-pennings** [comment]
Hi John,

I need some more clues to solve this.

If you inspect the ino file, the `setup()` function, you see

```
  // Flash
  Serial.print("setup: starting flash of '");
  Serial.print(image_name);
  Serial.println("' in 5 seconds");
  delay(5000);
  Serial.println("");
  ok= ccs811.flash(image_data, sizeof(image_data));
```

so after the message `setup: starting flash of 'CCS811_FW_App_v2-0-0.bin' in 5 seconds` the `flash()` function is called. That function starts as follows.

```
bool CCS811::flash(const uint8_t * image, int size) {
    ...
    wake_up();
    // Try to ping CCS811 (can we reach CCS811 via I2C?)
    PRINT(F("ccs811: ping "));
```

This means that after the message `setup: starting flash of 'CCS811_FW_App_v2-0-0.bin' in 5 seconds` the you must see `ccs811: ping ok` or `ccs811: ping FAILED`.

If you don't get that, something very funny is going on.
