### ISSUE TITLE
Downgrade to CCS811 Old Firmware v1.0.0

### ISSUE THREAD

**Issue by daferdur** [maarten-pennings/CCS811#49]
Hi guys!
I've modified my chinesse CSS811 board and soldered a 10k SMD NTC and a 10k SMD Resitor (R3 and R4 in original schematic) in orther to get Temperature readings.
The fact was that I had this board updated to firmware version 2.0.1 and it wasn't impossible to get temperature readings with this firmware.

So after a lot of searching Internet, I've found the old firmware to get temperature readings. 
And of course downgraded it with success.

Here you have that firmware.
[ccs811_fw_app_1v0p0.bin.zip](https://github.com/maarten-pennings/CCS811/files/4638037/ccs811_fw_app_1v0p0.bin.zip)

Hope it will serve to somebody.

**Comment by maarten-pennings** [comment]
Thanks. I'll add it to the repo. Where did find it?

**Comment by daferdur** [comment]
https://github.com/ryankurte/efm32-base/blob/master/hardware/kit/common/bsp/thunderboard/ccs811_fw_app_1v0p0.bin

**Comment by daferdur** [comment]
![HTB1O9wlavvsK1Rjy0Fiq6zwtXXaL](https://user-images.githubusercontent.com/54472249/82156408-34a74c00-987b-11ea-823f-684cd652c7e9.jpg)

Here you can see R3 qnd R4

**Comment by daferdur** [comment]
![IMG-20200516-WA0002](https://user-images.githubusercontent.com/54472249/82156517-b008fd80-987b-11ea-9bb0-fdeec258ea56.jpg)

And here my updated CSS811 board.

**Comment by maarten-pennings** [comment]
Nice! 

I didn't realize the board had the mounting pads already, 

Thanks for the 1.0.0 bin file; I have added it to the repo.

I've also changed the python script. The old one was still working for me, so I'm not sure what was the problem for you. It now uses f-strings.

**Comment by daferdur** [comment]
Thanks to you for your contribution.
