### ISSUE TITLE
CCS811 firmware demoted to version 1.1.0

### ISSUE THREAD

**Issue by wangmings** [maarten-pennings/CCS811#53]
CCS811 firmware demoted to version 1.1.0

CCS811 firmware demoted to version 1.1.0
Who knows how to downgrade from 2.0.0 to 1.1.0! No firmware version 1.1.0 was found in the warehouse

**Comment by maarten-pennings** [comment]
Do you really need 1.1.0? Is there a 1.1.0?

**Comment by wangmings** [comment]
Does it appear that there is no firmware version 1.1.0

**Comment by JsBergbau** [comment]
Does anyone know the difference between firmware version 1.1.0 and 1.0.0? Would also be interested in a bin file for flashing 1.1.0, if anybody should stumble across it.
