### ISSUE TITLE
begin() required before flash() ?

### ISSUE THREAD

**Issue by ilnadi** [maarten-pennings/CCS811#55]
trying to set up startup in a loop so if flash gets disrupted, etc, then we'll try again.
In the flash ino example begin() is called before and again after flashing.  this makes for an awkward loop.

Question: can flash() be run without begin() first?
i.e.
   init();
   do
   {
      if (application_version() < 0x2000)
      {
         flash();
      }
      begin();
   } while (errorHappened);

**Comment by maarten-pennings** [comment]
Begin() resets the ccs811 chip, gets some version data, and brings the chip in a known state.

**Comment by ilnadi** [comment]
ok, thanks
