### ISSUE TITLE
version checking functions have wrong comment, I think

### ISSUE THREAD

**Issue by Habbie** [maarten-pennings/CCS811#67]
https://github.com/maarten-pennings/CCS811/blob/e9bba3611c3d9544732c45d0951f26c4d79898db/src/ccs811.cpp#L260 says `returns 0 on I2C failure` but reading the code I get the impression failure yields `-1`.

I did not run the code - I was just reading it for inspiration, so it's possible I missed something.

If it's true, it also appears to apply to the bootloader and appliication version calls.

**Comment by maarten-pennings** [comment]
You are right. Fixed them in v11.

**Comment by Habbie** [comment]
bedankt!
